# Generated by Django 3.0 on 2019-12-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnsomething', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
