# Generated by Django 3.0 on 2020-01-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnsomething', '0002_article_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmark',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
