# Generated by Django 3.0 on 2020-01-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnsomething', '0003_auto_20200103_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.TextField(default=''),
        ),
    ]
